# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 00:52
from __future__ import unicode_literals

import core.users.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=80)),
                ('education', models.CharField(max_length=90)),
                ('age', models.DateField()),
                ('document_type', models.CharField(choices=[('CI', 'CEDULA DE IDENTIDAD'), ('PA', 'PASAPORTE'), ('DNI', 'DOCUMENTO DE IDENTIDAD')], max_length=4)),
                ('document_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('document_type', models.CharField(choices=[('CI', 'CEDULA DE IDENTIDAD'), ('PA', 'PASAPORTE'), ('DNI', 'DOCUMENTO DE IDENTIDAD')], max_length=4)),
                ('document_number', models.CharField(max_length=15)),
                ('university', models.CharField(max_length=30)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Education')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', core.users.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
