# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='schools',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
            preserve_default=False,
        ),
    ]
